In [15]:
import numpy as np
lst = [[1,2,3],[4,5,6],[7,8,9]]
array = np.array(lst)
print(array)
print(array.T)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [26]:
d1=np.arange(1,9).reshape(2,4)
d2=np.arange(11,19).reshape(2,4)
print(np.append(d1,d2,axis=0))
print(np.append(d1,d2,axis=1))
print(np.append(d1,d2))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [11 12 13 14]
 [15 16 17 18]]
[[ 1  2  3  4 11 12 13 14]
 [ 5  6  7  8 15 16 17 18]]
[ 1  2  3  4  5  6  7  8 11 12 13 14 15 16 17 18]


In [33]:
d1 = [[[1, 2], [3, 4]],[[4,5],[5,6]]]
d1 = np.array(d1)
d1.resize(3,4 ,2)
print(d1)
d2 = d1.view()
print(d2)
d1[2,3]  = 100
print(d1)
print(d2)

[[[1 2]
  [3 4]
  [4 5]
  [5 6]]

 [[0 0]
  [0 0]
  [0 0]
  [0 0]]

 [[0 0]
  [0 0]
  [0 0]
  [0 0]]]
[[[1 2]
  [3 4]
  [4 5]
  [5 6]]

 [[0 0]
  [0 0]
  [0 0]
  [0 0]]

 [[0 0]
  [0 0]
  [0 0]
  [0 0]]]
[[[  1   2]
  [  3   4]
  [  4   5]
  [  5   6]]

 [[  0   0]
  [  0   0]
  [  0   0]
  [  0   0]]

 [[  0   0]
  [  0   0]
  [  0   0]
  [100 100]]]
[[[  1   2]
  [  3   4]
  [  4   5]
  [  5   6]]

 [[  0   0]
  [  0   0]
  [  0   0]
  [  0   0]]

 [[  0   0]
  [  0   0]
  [  0   0]
  [100 100]]]


In [ ]:
print(np.zeros((2,3)),end="\n\n")# 全 0
print(np.ones((2,3)),end="\n\n")# 全 1
print(np.eye(3),end="\n\n")# 單位矩陣
print(np.arange(0,10,2),end="\n\n")#從0到10，步長為2
print(np.linspace(0,1,5),end="\n\n")#從0到1，取5個點

In [ ]:
_arrA=np.array([[1,2,3], [4,5,6]])
print(_arrA)
print(_arrA.shape)# 維度
print(_arrA.ndim)# 幾維
print(_arrA.size)# 總元素數
print(_arrA.dtype)# 型別
_arrB=_arrA.reshape(3,2)# 重新塑形
print(_arrA,_arrB,sep="\n\n")


In [ ]:
_arrA=np.array([10,20,30,40])

print(_arrA[0])# 10
print(_arrA[-1])# 40
print(_arrA[1:3])# [20 30]
_arrA = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print(_arrA[0, 1])     # 2
print(_arrA[:, 1])     # 第2欄
print(_arrA[1, :])     # 第2列

In [ ]:
import numpy as np
np.random.seed(0) # 設定隨機種子，使得每次執行都得到相同的隨機數
print(np.random.rand(3, 4))
print(np.random.rand(3, 4))

# 從列表中隨機選擇3個元素，不允許重複
a = np.random.choice([1, 2, 3, 4, 5], size=3, replace=False) 
print(np.random.shuffle(a))

In [39]:
import numpy as np
d1 = np.arange(0,36).reshape(6,6)
print(d1)
print(d1[0::3,3:6])

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]
[[ 3  4  5]
 [21 22 23]]


In [ ]:
import numpy as np

# d1 = np.array([])
# for i in range(6):
#     a = np.arange(0+i*10,6+i*10)
#     d1 = np.append(d1, a,axis=0)
d1 = np.array(range(60)).reshape(6,10)[:,0:6]
d2 = d1.reshape(6,6)
print(f"陣列:\n{d2}")
d3 = d2[0::5,0::5]
print(f"四個角落:\n{d3}")
d4 = d2[2:4,3:5]
print(f"黃框:\n{d4}")

for i in range(6):
    print("當行總和：", np.sum(d2[i,:]))
    
print("當列總和：", np.sum)

陣列:
[[ 0  1  2  3  4  5]
 [10 11 12 13 14 15]
 [20 21 22 23 24 25]
 [30 31 32 33 34 35]
 [40 41 42 43 44 45]
 [50 51 52 53 54 55]]
四個角落:
[[ 0  5]
 [50 55]]
黃框:
[[23 24]
 [33 34]]
當行總和： 15
當行總和： 75
當行總和： 135
當行總和： 195
當行總和： 255
當行總和： 315
